import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { motion, AnimatePresence } from 'framer-motion'
import axios from 'axios'
import toast from 'react-hot-toast'
import { useAuth } from '../context/AuthContext'
import AnimatedBackground from '../components/AnimatedBackground'
import { API_URL } from '../config'
import jsPDF from 'jspdf'
import {
  ArrowLeft, FileText, Upload, Wand2, Download,
  Copy, RefreshCw, CheckCircle, Briefcase, Building2
} from 'lucide-react'

export default function CoverLetter() {
  const { user } = useAuth()
  const navigate = useNavigate()
  const [file, setFile] = useState(null)
  const [jobTitle, setJobTitle] = useState('')
  const [companyName, setCompanyName] = useState('')
  const [jobDescription, setJobDescription] = useState('')
  const [tone, setTone] = useState('Professional')
  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState(null)
  const [copied, setCopied] = useState(false)
  const [editMode, setEditMode] = useState(false)
  const [editedLetter, setEditedLetter] = useState('')

  const tones = ['Professional', 'Confident', 'Enthusiastic', 'Creative']

  const generate = async () => {
    if (!jobDescription.trim()) return toast.error('Job description is required')
    setLoading(true)
    try {
      const formData = new FormData()
      if (file) formData.append('resume', file)
      formData.append('jobDescription', jobDescription)
      formData.append('jobTitle', jobTitle)
      formData.append('companyName', companyName)
      formData.append('tone', tone)

      const { data } = await axios.post(`${API_URL}/api/coverletter/generate`, formData, {
        headers: {
          'Content-Type': 'multipart/form-data',
          Authorization: `Bearer ${user.token}`
        }
      })
      setResult(data)
      setEditedLetter(data.coverLetter)
      toast.success('Cover letter generated!')
    } catch (err) {
      toast.error(err.response?.data?.message || 'Generation failed')
    } finally {
      setLoading(false)
    }
  }

  const copyToClipboard = () => {
    navigator.clipboard.writeText(editMode ? editedLetter : result.coverLetter)
    setCopied(true)
    toast.success('Copied to clipboard!')
    setTimeout(() => setCopied(false), 2000)
  }

  const downloadPDF = () => {
    const doc = new jsPDF()
    const content = editMode ? editedLetter : result.coverLetter

    doc.setFillColor(127, 119, 221)
    doc.rect(0, 0, 210, 25, 'F')
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(16)
    doc.setFont(undefined, 'bold')
    doc.text('Cover Letter', 14, 16)
    doc.setFontSize(10)
    doc.setFont(undefined, 'normal')
    if (result.jobTitle) doc.text(`${result.jobTitle}${result.companyName ? ` — ${result.companyName}` : ''}`, 100, 16)

    doc.setTextColor(20, 20, 20)
    doc.setFontSize(11)
    const lines = doc.splitTextToSize(content, 180)
    let y = 35
    lines.forEach(line => {
      if (y > 270) { doc.addPage(); y = 20 }
      doc.text(line, 14, y)
      y += 7
    })

    doc.setFontSize(8)
    doc.setTextColor(150, 150, 150)
    doc.text('Generated by CareerLaunch AI', 14, 290)

    doc.save(`Cover_Letter_${result.companyName || 'Application'}.pdf`)
    toast.success('PDF downloaded!')
  }

  return (
    <div className="min-h-screen bg-dark-900 text-white relative">
      <AnimatedBackground />

      <div className="relative z-10">
        {/* Header */}
        <div className="bg-dark-800/90 backdrop-blur-xl border-b border-white/5 px-6 py-4 flex items-center gap-4">
          <button onClick={() => navigate('/dashboard')}
            className="p-2 hover:bg-white/5 rounded-lg transition-colors">
            <ArrowLeft size={20} className="text-gray-400" />
          </button>
          <div>
            <h1 className="text-xl font-bold">Cover Letter Generator</h1>
            <p className="text-sm text-gray-400">AI-powered, tailored to your resume & job</p>
          </div>
        </div>

        <div className="max-w-5xl mx-auto px-6 py-8">
          <AnimatePresence mode="wait">

            {/* Input Form */}
            {!result && (
              <motion.div key="form" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -20 }} className="grid lg:grid-cols-2 gap-6">

                {/* Left — Job Details */}
                <div className="space-y-5">
                  <div className="glass rounded-2xl p-6 border border-white/5">
                    <h2 className="font-semibold mb-4 flex items-center gap-2">
                      <Briefcase size={18} className="text-primary-400" /> Job Details
                    </h2>

                    <div className="space-y-3">
                      <div>
                        <label className="block text-sm text-gray-400 mb-1.5">Job Title</label>
                        <input value={jobTitle} onChange={e => setJobTitle(e.target.value)}
                          placeholder="e.g. SDE-1, Frontend Developer"
                          className="w-full bg-dark-700 border border-white/10 rounded-xl px-4 py-2.5 text-white placeholder-gray-600 focus:outline-none focus:border-primary-400 text-sm" />
                      </div>

                      <div>
                        <label className="block text-sm text-gray-400 mb-1.5">Company Name</label>
                        <input value={companyName} onChange={e => setCompanyName(e.target.value)}
                          placeholder="e.g. Amazon, TCS, Flipkart"
                          className="w-full bg-dark-700 border border-white/10 rounded-xl px-4 py-2.5 text-white placeholder-gray-600 focus:outline-none focus:border-primary-400 text-sm" />
                      </div>

                      <div>
                        <label className="block text-sm text-gray-400 mb-1.5">Tone</label>
                        <div className="grid grid-cols-2 gap-2">
                          {tones.map(t => (
                            <button key={t} onClick={() => setTone(t)}
                              className={`py-2 rounded-xl text-sm font-medium transition-all ${tone === t ? 'bg-primary-600 text-white' : 'bg-dark-700 text-gray-400 hover:bg-dark-600'}`}>
                              {t}
                            </button>
                          ))}
                        </div>
                      </div>
                    </div>
                  </div>

                  {/* Resume Upload */}
                  <div className="glass rounded-2xl p-6 border border-white/5">
                    <h2 className="font-semibold mb-4 flex items-center gap-2">
                      <FileText size={18} className="text-teal-400" /> Your Resume
                      <span className="text-xs text-gray-500 font-normal ml-1">(Optional but recommended)</span>
                    </h2>

                    <div onClick={() => document.getElementById('coverFileInput').click()}
                      className={`border-2 border-dashed rounded-xl p-5 text-center cursor-pointer transition-all
                        ${file ? 'border-teal-500/50 bg-teal-900/10' : 'border-white/10 hover:border-primary-600/50 hover:bg-white/5'}`}>
                      <input id="coverFileInput" type="file" accept=".pdf,.docx,.txt" className="hidden"
                        onChange={e => setFile(e.target.files[0])} />
                      {file ? (
                        <div>
                          <CheckCircle size={28} className="text-teal-400 mx-auto mb-2" />
                          <p className="text-sm text-white font-medium">{file.name}</p>
                          <button onClick={e => { e.stopPropagation(); setFile(null) }}
                            className="text-xs text-gray-500 hover:text-red-400 mt-1">Remove</button>
                        </div>
                      ) : (
                        <div>
                          <Upload size={28} className="text-gray-600 mx-auto mb-2" />
                          <p className="text-sm text-gray-400">Upload resume for personalized letter</p>
                          <p className="text-xs text-gray-600 mt-1">PDF, DOCX, TXT</p>
                        </div>
                      )}
                    </div>
                  </div>
                </div>

                {/* Right — Job Description */}
                <div className="glass rounded-2xl p-6 border border-white/5 flex flex-col">
                  <h2 className="font-semibold mb-4 flex items-center gap-2">
                    <Building2 size={18} className="text-orange-400" /> Job Description
                    <span className="text-xs text-red-400 font-normal ml-1">*Required</span>
                  </h2>

                  <textarea value={jobDescription} onChange={e => setJobDescription(e.target.value)}
                    placeholder="Paste the job description here...&#10;&#10;Include requirements, responsibilities, and company info for best results."
                    className="flex-1 min-h-[320px] w-full bg-dark-700 border border-white/10 rounded-xl px-4 py-3 text-white placeholder-gray-600 focus:outline-none focus:border-primary-400 text-sm resize-none" />

                  <button onClick={generate} disabled={loading || !jobDescription.trim()}
                    className="mt-4 w-full bg-primary-600 hover:bg-primary-400 disabled:opacity-40 text-white py-3.5 rounded-xl font-semibold transition-all duration-200 flex items-center justify-center gap-2">
                    {loading ? (
                      <><div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin" /> Generating...</>
                    ) : (
                      <><Wand2 size={20} /> Generate Cover Letter</>
                    )}
                  </button>
                </div>
              </motion.div>
            )}

            {/* Result */}
            {result && (
              <motion.div key="result" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>

                <div className="flex items-center justify-between mb-6">
                  <div>
                    <h2 className="text-xl font-bold">Your Cover Letter</h2>
                    {result.jobTitle && (
                      <p className="text-sm text-gray-400 mt-0.5">
                        {result.jobTitle}{result.companyName && ` — ${result.companyName}`}
                      </p>
                    )}
                  </div>
                  <div className="flex items-center gap-2">
                    <button onClick={() => setEditMode(!editMode)}
                      className={`px-4 py-2 rounded-xl text-sm font-medium transition-all border ${editMode ? 'bg-primary-600 text-white border-primary-600' : 'glass border-white/10 text-gray-400 hover:text-white'}`}>
                      {editMode ? 'Done Editing' : 'Edit'}
                    </button>
                    <button onClick={copyToClipboard}
                      className="flex items-center gap-2 px-4 py-2 glass rounded-xl text-sm text-gray-400 hover:text-white border border-white/10 transition-all">
                      {copied ? <CheckCircle size={16} className="text-teal-400" /> : <Copy size={16} />}
                      {copied ? 'Copied!' : 'Copy'}
                    </button>
                    <button onClick={downloadPDF}
                      className="flex items-center gap-2 px-4 py-2 bg-primary-600 hover:bg-primary-400 rounded-xl text-sm text-white transition-all">
                      <Download size={16} /> PDF
                    </button>
                  </div>
                </div>

                {/* Letter Content */}
                <div className="glass rounded-2xl p-8 border border-white/5 mb-6">
                  {/* Formal header */}
                  <div className="mb-6 pb-6 border-b border-white/5">
                    <p className="text-gray-300 font-medium">{user?.name}</p>
                    <p className="text-gray-500 text-sm">Placement Aspirant | {new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</p>
                  </div>

                  <p className="text-gray-400 mb-4">Dear Hiring Manager,</p>

                  {editMode ? (
                    <textarea value={editedLetter} onChange={e => setEditedLetter(e.target.value)}
                      className="w-full min-h-[320px] bg-dark-700 border border-primary-400/30 rounded-xl px-4 py-3 text-gray-200 text-sm leading-relaxed resize-none focus:outline-none focus:border-primary-400" />
                  ) : (
                    <div className="text-gray-200 text-sm leading-relaxed whitespace-pre-line">
                      {result.coverLetter}
                    </div>
                  )}

                  <div className="mt-6 pt-6 border-t border-white/5">
                    <p className="text-gray-400 text-sm">Sincerely,</p>
                    <p className="text-white font-medium mt-1">{user?.name}</p>
                  </div>
                </div>

                {/* Regenerate */}
                <button onClick={() => { setResult(null); setEditedLetter('') }}
                  className="w-full glass border border-white/10 hover:border-primary-600/50 text-gray-400 hover:text-white py-3 rounded-xl text-sm font-medium transition-all flex items-center justify-center gap-2">
                  <RefreshCw size={16} /> Generate Another
                </button>

              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>
    </div>
  )
}