import StaticPage from './StaticPage'

export default function TermsOfService() {
  return (
    <StaticPage title="Terms of Service" lastUpdated="June 2026">
      <p>
        By accessing or using CareerLaunch AI, you agree to be bound by these Terms of Service. Please read them carefully before using the platform.
      </p>

      <h3 className="text-xl font-semibold text-white pt-4">Use of the Platform</h3>
      <p>
        CareerLaunch AI is provided free of charge for educational and placement preparation purposes. You agree to use the platform only for lawful purposes and not to misuse any AI features, including attempting to extract harmful or inappropriate content.
      </p>

      <h3 className="text-xl font-semibold text-white pt-4">AI-Generated Content Disclaimer</h3>
      <p>
        Resume scores, interview feedback, roadmaps, and chatbot responses are generated by AI models and are intended as guidance only. While we strive for accuracy, AI-generated content may occasionally contain errors or incomplete information. Always use your own judgment alongside our recommendations.
      </p>

      <h3 className="text-xl font-semibold text-white pt-4">User Content</h3>
      <p>
        You retain ownership of any resumes, notes, or documents you upload. By uploading content, you grant us permission to process it temporarily through our AI services to deliver the requested feature (e.g., resume analysis, chatbot responses).
      </p>

      <h3 className="text-xl font-semibold text-white pt-4">Account Responsibility</h3>
      <p>
        You are responsible for maintaining the confidentiality of your account credentials and for all activities under your account.
      </p>

      <h3 className="text-xl font-semibold text-white pt-4">Limitation of Liability</h3>
      <p>
        CareerLaunch AI is provided "as is" without warranties of any kind. We are not liable for any placement outcomes, interview results, or career decisions made based on platform recommendations.
      </p>

      <h3 className="text-xl font-semibold text-white pt-4">Changes to Terms</h3>
      <p>
        We may update these terms from time to time. Continued use of the platform after changes constitutes acceptance of the updated terms.
      </p>
    </StaticPage>
  )
}